[tool.black]
line-length = 120
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 120
include_trailing_comma = true
use_parentheses = true
multi_line_output = 3
force_grid_wrap = 0
combine_as_imports = true

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203", "W503"]
exclude = [
  ".git",
  "__pycache__",
  "build",
  "dist",
  "node_modules",
  ".venv",
  "venv",
]
