AWSTemplateFormatVersion: "2010-09-09"
Description: Subscriber Migration Portal Infrastructure

Parameters:
  DomainName:
    Type: String
    Description: Your domain name for frontend

Resources:

  # Frontend S3 bucket
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DomainName}-frontend-bucket"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  # DynamoDB table for subscribers
  SubscriberTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SubscriberTable
      AttributeDefinitions:
        - AttributeName: subscriberId
          AttributeType: S
      KeySchema:
        - AttributeName: subscriberId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # DynamoDB table for audit logs
  AuditLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AuditLogTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # Health check example (optional, can remove if not used)
  HealthCheckPrimary:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        IPAddress: "1.1.1.1"
        Port: 80
        Type: HTTP
        ResourcePath: /

  HealthCheckSecondary:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        IPAddress: "1.1.1.2"
        Port: 80
        Type: HTTP
        ResourcePath: /

Outputs:
  FrontendURL:
    Description: URL for frontend S3 bucket
    Value: !Sub "http://${FrontendBucket}.s3-website.${AWS::Region}.amazonaws.com"

  SubscriberTableName:
    Description: DynamoDB table name for subscribers
    Value: !Ref SubscriberTable

  AuditLogTableName:
    Description: DynamoDB table name for audit logs
    Value: !Ref AuditLogTable
