AWSTemplateFormatVersion: "2025-10-18"
Description: Full Subscriber Migration Portal Infrastructure

Parameters:
  DomainName:
    Type: String
    Description: Optional domain name for the frontend site

Resources:

  # ----------------------------------------------------------------------
  # S3 Bucket: Frontend static website hosting (also stores Lambda zip)
  # ----------------------------------------------------------------------
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "subscriber-portal-${AWS::AccountId}-${AWS::Region}"
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # Public read policy for static website access
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${FrontendBucket.Arn}/*"

  # ----------------------------------------------------------------------
  # DynamoDB Tables: Subscriber data & Audit logs
  # ----------------------------------------------------------------------
  SubscriberTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "SubscriberTable-${AWS::AccountId}-${AWS::Region}"
      AttributeDefinitions:
        - AttributeName: subscriberId
          AttributeType: S
      KeySchema:
        - AttributeName: subscriberId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  AuditLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "AuditLogTable-${AWS::AccountId}-${AWS::Region}"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # ----------------------------------------------------------------------
  # IAM Role: Execution permissions for backend Lambda
  # ----------------------------------------------------------------------
  BackendLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "SubscriberBackendRole-${AWS::AccountId}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  # ----------------------------------------------------------------------
  # Lambda Function: Backend business logic handler
  # ----------------------------------------------------------------------
  BackendLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "subscriber-backend-${AWS::AccountId}-${AWS::Region}"
      Handler: app.lambda_handler
      Runtime: python3.11
      Role: !GetAtt BackendLambdaRole.Arn
      Code:
        S3Bucket: !Ref FrontendBucket
        S3Key: backend.zip  # real uploaded backend zip

# ----------------------------------------------------------------------
# Outputs: Key resources exported for reference
# ----------------------------------------------------------------------
Outputs:
  FrontendURL:
    Description: URL of the deployed frontend (S3 static site)
    Value: !Sub "http://${FrontendBucket}.s3-website.${AWS::Region}.amazonaws.com"

  SubscriberTableName:
    Description: Name of the DynamoDB subscriber table
    Value: !Ref SubscriberTable

  AuditLogTableName:
    Description: Name of the DynamoDB audit log table
    Value: !Ref AuditLogTable

  BackendLambdaName:
    Description: Name of the backend Lambda function
    Value: !Ref BackendLambda
