AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Subscriber Migration Portal - Reuse existing VPC and subnets (conflict-free)'

Parameters:
  Stage:
    Type: String
    Default: 'prod'
    AllowedValues: ['dev','test','prod']
  CorsOrigins:
    Type: String
    Default: 'https://yourdomain.com'
  JwtSecret:
    Type: String
    NoEcho: true
  BucketSuffix:
    Type: String
    Default: '20251031'
  DbInstanceClass:
    Type: String
    Default: 'db.t3.micro'
    AllowedValues:
      - 'db.t3.micro'
      - 'db.t2.micro'
  DbAllocatedStorage:
    Type: Number
    Default: 20
  # VPC and Subnet Parameters - reuse existing infrastructure
  VpcId:
    Type: String
    Description: 'Existing VPC ID to use'
    Default: 'vpc-0123456789abcdef0'  # Will be auto-detected
  PrivateSubnetId1:
    Type: String
    Description: 'First private subnet ID'
    Default: 'subnet-0123456789abcdef0'  # Will be auto-detected
  PrivateSubnetId2:
    Type: String
    Description: 'Second private subnet ID' 
    Default: 'subnet-0123456789abcdef1'  # Will be auto-detected
  PublicSubnetId1:
    Type: String
    Description: 'First public subnet ID (optional)'
    Default: 'subnet-0123456789abcdef2'  # Will be auto-detected
  PublicSubnetId2:
    Type: String
    Description: 'Second public subnet ID (optional)'
    Default: 'subnet-0123456789abcdef3'  # Will be auto-detected

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11
    Environment:
      Variables:
        STAGE: !Ref Stage
        CORS_ORIGINS: !Ref CorsOrigins
        AWS_STACK_NAME: !Sub '${AWS::StackName}'
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: !Sub "'${CorsOrigins}'"
      MaxAge: "'600'"

Resources:
  # ---------------- Security Groups (application-specific) ----------------
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Lambda security group with egress
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  RdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: RDS MySQL ingress from Lambda
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref LambdaSecurityGroup

  VpcEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: VPC Endpoint security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref LambdaSecurityGroup

  # ---------------- VPC Endpoints (using existing subnets) ----------------
  SecretsManagerEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      VpcEndpointType: Interface
      SubnetIds: [!Ref PrivateSubnetId1, !Ref PrivateSubnetId2]
      SecurityGroupIds: [!Ref VpcEndpointSecurityGroup]
      PrivateDnsEnabled: true

  LogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.logs'
      VpcEndpointType: Interface
      SubnetIds: [!Ref PrivateSubnetId1, !Ref PrivateSubnetId2]
      SecurityGroupIds: [!Ref VpcEndpointSecurityGroup]
      PrivateDnsEnabled: true

  # ---------------- S3 Bucket ----------------
  UploadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-uploads-${BucketSuffix}'
      VersioningConfiguration: { Status: Enabled }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # ---------------- DynamoDB ----------------
  SubscribersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-subscribers-${BucketSuffix}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: uid, AttributeType: S }
        - { AttributeName: status, AttributeType: S }
        - { AttributeName: plan_id, AttributeType: S }
      KeySchema: [{ AttributeName: uid, KeyType: HASH }]
      GlobalSecondaryIndexes:
        - IndexName: status-index
          KeySchema: [{ AttributeName: status, KeyType: HASH }]
          Projection: { ProjectionType: ALL }
        - IndexName: plan-index
          KeySchema: [{ AttributeName: plan_id, KeyType: HASH }]
          Projection: { ProjectionType: ALL }

  SettingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-settings-${BucketSuffix}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: [{ AttributeName: sk, AttributeType: S }]
      KeySchema: [{ AttributeName: sk, KeyType: HASH }]

  MigrationJobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-jobs-${BucketSuffix}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: job_id, AttributeType: S }
        - { AttributeName: job_type, AttributeType: S }
        - { AttributeName: created_at, AttributeType: S }
      KeySchema: [{ AttributeName: job_id, KeyType: HASH }]
      GlobalSecondaryIndexes:
        - IndexName: job-type-index
          KeySchema:
            - { AttributeName: job_type, KeyType: HASH }
            - { AttributeName: created_at, KeyType: RANGE }
          Projection: { ProjectionType: ALL }

  # ---------------- Secrets + RDS MySQL ----------------
  LegacyDbSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}-legacy-db-${BucketSuffix}'
      Description: 'Credentials for RDS MySQL'
      GenerateSecretString:
        SecretStringTemplate: '{"username":"admin","dbname":"legacydb"}'
        GenerateStringKey: 'password'
        PasswordLength: 24
        ExcludeCharacters: '"@/\'

  LegacyDbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub '${AWS::StackName}-rds-subnet-${BucketSuffix}'
      DBSubnetGroupDescription: Private subnets for RDS
      SubnetIds: [!Ref PrivateSubnetId1, !Ref PrivateSubnetId2]

  LegacyDb:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub '${AWS::StackName}-legacy-${BucketSuffix}'
      Engine: mysql
      EngineVersion: '5.7.44'  # MySQL 5.7 for compatibility
      DBInstanceClass: !Ref DbInstanceClass
      AllocatedStorage: !Ref DbAllocatedStorage
      StorageType: gp2
      PubliclyAccessible: false
      MultiAZ: false
      VPCSecurityGroups: [!Ref RdsSecurityGroup]
      DBSubnetGroupName: !Ref LegacyDbSubnetGroup
      MasterUsername: !Sub '{{resolve:secretsmanager:${LegacyDbSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${LegacyDbSecret}::password}}'
      DBName: !Sub '{{resolve:secretsmanager:${LegacyDbSecret}::dbname}}'
      BackupRetentionPeriod: 1
      EnablePerformanceInsights: false
      MonitoringInterval: 0

  # ---------------- IAM Roles & Policies ----------------
  StepFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: states.amazonaws.com }
            Action: sts:AssumeRole

  LambdaVpcRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

  LambdaPublicRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  StepFunctionInvokeLambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWS::StackName}-sfn-lambda'
      Roles: [!Ref StepFunctionExecutionRole]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: ['lambda:InvokeFunction']
            Resource: ['*']

  LambdaVpcExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWS::StackName}-lambda-vpc-exec'
      Roles: [!Ref LambdaVpcRole]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: ['dynamodb:*']
            Resource:
              - !GetAtt SubscribersTable.Arn
              - !Sub '${SubscribersTable.Arn}/index/*'
              - !GetAtt MigrationJobsTable.Arn
              - !Sub '${MigrationJobsTable.Arn}/index/*'
              - !GetAtt SettingsTable.Arn
          - Effect: Allow
            Action: ['s3:*','secretsmanager:GetSecretValue','rds:DescribeDBInstances','states:*','cloudformation:DescribeStacks']
            Resource: '*'

  # ---------------- Lambda Layers ----------------
  PymysqlLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${AWS::StackName}-pymysql'
      Description: PyMySQL library for database operations
      ContentUri: layers/pymysql/
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.11

  # ---------------- Schema Initializer Lambda ----------------
  SchemaInitializerFunction:
    Type: AWS::Serverless::Function
    DependsOn:
      - LegacyDb
      - LegacyDbSecret
    Properties:
      FunctionName: !Sub '${AWS::StackName}-schema-initializer'
      Role: !GetAtt LambdaVpcRole.Arn
      CodeUri: lambda/schema-init/
      Handler: index.handler
      Runtime: python3.11
      Timeout: 300
      MemorySize: 512
      Layers:
        - !Ref PymysqlLayer
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: [!Ref PrivateSubnetId1, !Ref PrivateSubnetId2]
      Environment:
        Variables:
          LEGACY_DB_SECRET_ARN: !Ref LegacyDbSecret
          LEGACY_DB_HOST: !GetAtt LegacyDb.Endpoint.Address
          AWS_STACK_NAME: !Sub '${AWS::StackName}'

  # ---------------- Application Lambdas ----------------
  OrchestratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaVpcRole.Arn
      CodeUri: lambda/migration/
      Handler: orchestrator.lambda_handler
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: [!Ref PrivateSubnetId1, !Ref PrivateSubnetId2]
      Environment:
        Variables:
          MIGRATION_JOBS_TABLE: !Ref MigrationJobsTable
          UPLOADS_BUCKET: !Ref UploadsBucket
      Events:
        UploadRequest: { Type: Api, Properties: { Path: /migration/upload, Method: POST } }
        CreateMigrationJob: { Type: Api, Properties: { Path: /migration/jobs, Method: POST } }
        CreateAuditJob: { Type: Api, Properties: { Path: /audit/jobs, Method: POST } }
        CreateExportJob: { Type: Api, Properties: { Path: /export/jobs, Method: POST } }
        GetJobStatus: { Type: Api, Properties: { Path: "/jobs/{id}", Method: GET } }
        CancelJob: { Type: Api, Properties: { Path: "/jobs/{id}/cancel", Method: POST } }
        ListJobs: { Type: Api, Properties: { Path: /jobs, Method: GET } }

  ValidateJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaVpcRole.Arn
      CodeUri: lambda/migration/
      Handler: validate_job.lambda_handler
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: [!Ref PrivateSubnetId1, !Ref PrivateSubnetId2]
      Environment:
        Variables:
          UPLOADS_BUCKET: !Ref UploadsBucket

  ProcessFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaVpcRole.Arn
      CodeUri: lambda/migration/
      Handler: process_file.lambda_handler
      Timeout: 900
      Layers:
        - !Ref PymysqlLayer
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: [!Ref PrivateSubnetId1, !Ref PrivateSubnetId2]
      Environment:
        Variables:
          SUBSCRIBERS_TABLE: !Ref SubscribersTable
          MIGRATION_JOBS_TABLE: !Ref MigrationJobsTable
          UPLOADS_BUCKET: !Ref UploadsBucket
          LEGACY_DB_SECRET_ARN: !Ref LegacyDbSecret
          LEGACY_DB_HOST: !GetAtt LegacyDb.Endpoint.Address

  ProcessAuditFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaVpcRole.Arn
      CodeUri: lambda/migration/
      Handler: process_audit.lambda_handler
      Timeout: 600
      Layers:
        - !Ref PymysqlLayer
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: [!Ref PrivateSubnetId1, !Ref PrivateSubnetId2]
      Environment:
        Variables:
          SUBSCRIBERS_TABLE: !Ref SubscribersTable
          MIGRATION_JOBS_TABLE: !Ref MigrationJobsTable
          UPLOADS_BUCKET: !Ref UploadsBucket
          LEGACY_DB_SECRET_ARN: !Ref LegacyDbSecret
          LEGACY_DB_HOST: !GetAtt LegacyDb.Endpoint.Address

  ProcessExportFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaVpcRole.Arn
      CodeUri: lambda/migration/
      Handler: process_export.lambda_handler
      Timeout: 600
      Layers:
        - !Ref PymysqlLayer
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: [!Ref PrivateSubnetId1, !Ref PrivateSubnetId2]
      Environment:
        Variables:
          SUBSCRIBERS_TABLE: !Ref SubscribersTable
          MIGRATION_JOBS_TABLE: !Ref MigrationJobsTable
          UPLOADS_BUCKET: !Ref UploadsBucket
          LEGACY_DB_SECRET_ARN: !Ref LegacyDbSecret
          LEGACY_DB_HOST: !GetAtt LegacyDb.Endpoint.Address

  SettingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaVpcRole.Arn
      CodeUri: lambda/settings/
      Handler: handler.lambda_handler
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: [!Ref PrivateSubnetId1, !Ref PrivateSubnetId2]
      Environment:
        Variables:
          SETTINGS_TABLE: !Ref SettingsTable
      Events:
        GetMode: { Type: Api, Properties: { Path: /settings/provisioning-mode, Method: GET } }
        PutMode: { Type: Api, Properties: { Path: /settings/provisioning-mode, Method: PUT } }

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaVpcRole.Arn
      CodeUri: lambda/auth/
      Handler: handler.lambda_handler
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: [!Ref PrivateSubnetId1, !Ref PrivateSubnetId2]
      Environment:
        Variables:
          JWT_SECRET: !Ref JwtSecret
      Events:
        Login: { Type: Api, Properties: { Path: /auth/login, Method: POST } }
        VerifyToken: { Type: Api, Properties: { Path: /auth/verify, Method: POST } }
        RefreshToken: { Type: Api, Properties: { Path: /auth/refresh, Method: POST } }

  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaPublicRole.Arn
      CodeUri: lambda/health/
      Handler: handler.lambda_handler
      Events:
        HealthCheck: { Type: Api, Properties: { Path: /health, Method: GET } }

  # ---------------- Step Functions ----------------
  MigrationWorkflow:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt StepFunctionExecutionRole.Arn
      DefinitionString: !Sub '{"StartAt":"Validate","States":{"Validate":{"Type":"Task","Resource":"arn:aws:states:::lambda:invoke","Parameters":{"FunctionName":"${ValidateJobFunction.Arn}","Payload.$":"$"},"Next":"Process"},"Process":{"Type":"Task","Resource":"arn:aws:states:::lambda:invoke","Parameters":{"FunctionName":"${ProcessFileFunction.Arn}","Payload.$":"$"},"End":true}}}'

  AuditWorkflow:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt StepFunctionExecutionRole.Arn
      DefinitionString: !Sub '{"StartAt":"Audit","States":{"Audit":{"Type":"Task","Resource":"arn:aws:states:::lambda:invoke","Parameters":{"FunctionName":"${ProcessAuditFunction.Arn}","Payload.$":"$"},"End":true}}}'

  ExportWorkflow:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt StepFunctionExecutionRole.Arn
      DefinitionString: !Sub '{"StartAt":"Export","States":{"Export":{"Type":"Task","Resource":"arn:aws:states:::lambda:invoke","Parameters":{"FunctionName":"${ProcessExportFunction.Arn}","Payload.$":"$"},"End":true}}}'

Outputs:
  ApiEndpoint:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}'
  UploadsBucketName:
    Value: !Ref UploadsBucket
  MigrationJobsTableName:
    Value: !Ref MigrationJobsTable
  SubscribersTableName:
    Value: !Ref SubscribersTable
  SettingsTableName:
    Value: !Ref SettingsTable
  MigrationWorkflowArn:
    Value: !Ref MigrationWorkflow
  AuditWorkflowArn:
    Value: !Ref AuditWorkflow
  ExportWorkflowArn:
    Value: !Ref ExportWorkflow
  LegacyDbSecretArn:
    Value: !Ref LegacyDbSecret
  LegacyDbHost:
    Value: !GetAtt LegacyDb.Endpoint.Address
  SchemaInitializerFunctionName:
    Value: !Ref SchemaInitializerFunction
    Description: Schema Initializer Lambda Name
    Export:
      Name: !Sub '${AWS::StackName}-schema-initializer-name'
  SchemaInitializerArn:
    Value: !GetAtt SchemaInitializerFunction.Arn
    Description: Schema Initializer Lambda ARN
    Export:
      Name: !Sub '${AWS::StackName}-schema-initializer-arn'