AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Subscriber Migration Portal - Full VPC architecture with free-tier RDS settings (t2.micro fallback)'

Parameters:
  Stage:
    Type: String
    Default: 'prod'
    AllowedValues: ['dev','test','prod']
  CorsOrigins:
    Type: String
    Default: 'https://yourdomain.com'
  JwtSecret:
    Type: String
    NoEcho: true
  BucketSuffix:
    Type: String
    Default: '20251031'
  VpcCidr:
    Type: String
    Default: '10.0.0.0/16'

Conditions:
  IsProd: !Equals [!Ref Stage, 'prod']

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11
    Environment:
      Variables:
        STAGE: !Ref Stage
        CORS_ORIGINS: !Ref CorsOrigins
        AWS_STACK_NAME: !Sub '${AWS::StackName}'
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: !Sub "'${CorsOrigins}'"
      MaxAge: "'600'"

Resources:
  # ... entire template retained from previous commit ...

  # Only the LegacyDB resource is modified below to use db.t2.micro
  LegacyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub '${AWS::StackName}-legacy-${BucketSuffix}'
      Engine: mysql
      EngineVersion: '8.0'
      DBInstanceClass: 'db.t2.micro'
      AllocatedStorage: 20
      StorageType: gp2
      PubliclyAccessible: false
      MultiAZ: false
      VPCSecurityGroups: [!Ref RdsSG]
      DBSubnetGroupName: !Ref LegacyDbSubnetGroup
      MasterUsername: !Sub '{{resolve:secretsmanager:${LegacyDbSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${LegacyDbSecret}::password}}'
      DBName: !Sub '{{resolve:secretsmanager:${LegacyDbSecret}::dbname}}'
      BackupRetentionPeriod: 1
      EnablePerformanceInsights: false
      MonitoringInterval: 0
    DependsOn: [PrivateSubnetARouteTableAssociation, PrivateSubnetBRouteTableAssociation]

Outputs:
  LegacyDbHost:
    Value: !GetAtt LegacyDB.Endpoint.Address
  LegacyDbSecretArn:
    Value: !Ref LegacyDbSecret
