name: 🩺 Health Check

on:
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-east-1
  FRONTEND_BUCKET: subscriber-migration-stack-prod-frontend
  API_GATEWAY_ID: hsebznxeu6

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - name: Set URLs
        id: set
        run: |
          echo "API_URL=https://${{ env.API_GATEWAY_ID }}.execute-api.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/prod" >> $GITHUB_ENV
          echo "FRONTEND_URL=http://${{ env.FRONTEND_BUCKET }}.s3-website-${{ env.AWS_DEFAULT_REGION }}.amazonaws.com" >> $GITHUB_ENV

      - name: Frontend check
        run: |
          CODE=$(curl -s -o /dev/null -w "%{http_code}" "$FRONTEND_URL")
          echo "Frontend: $CODE"
          if [ "$CODE" != "200" ]; then
            echo "Frontend not 200"
            exit 1
          fi

      - name: API health
        run: |
          CODE=$(curl -s -w "%{http_code}" -o /tmp/health.json "$API_URL/api/health")
          echo "API Health: $CODE" && cat /tmp/health.json || true
          if [ "$CODE" != "200" ]; then
            echo "API health failed"; exit 1; fi

      - name: Authentication
        run: |
          CODE=$(curl -s -X POST "$API_URL/api/auth/login" \
            -H "Content-Type: application/json" \
            -d '{"username":"admin","password":"Admin@123"}' \
            -w "%{http_code}" -o /tmp/auth.json)
          echo "Auth: $CODE" && cat /tmp/auth.json || true
          if [ "$CODE" != "200" ]; then echo "Auth failed"; exit 1; fi

      - name: Legacy DB (soft check)
        run: |
          CODE=$(curl -s "$API_URL/api/legacy/test" -w "%{http_code}" -o /tmp/legacy.json)
          echo "Legacy: $CODE" && cat /tmp/legacy.json || true
          if [ "$CODE" != "200" ]; then echo "Warning: Legacy DB not connected (VPC/SG?)"; fi

      - name: Dashboard stats
        run: |
          CODE=$(curl -s "$API_URL/api/dashboard/stats" -w "%{http_code}" -o /tmp/stats.json)
          echo "Stats: $CODE" && cat /tmp/stats.json || true
          if [ "$CODE" != "200" ]; then echo "Warning: Stats not 200"; fi

      - name: Summary
        run: |
          echo "✅ Health check completed. See steps above for details."
