name: 🎆 Auto-Deploy on Changes

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/main-deploy.yml'
      - 'README.md'

jobs:
  trigger:
    name: 🚀 Trigger Main Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 📢 Trigger Main Deployment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'main-deploy.yml',
              ref: 'main'
            });
            console.log('🚀 Main deployment triggered successfully!');
          github-token: ${{ secrets.GITHUB_TOKEN }}